import { Difficulty, Problem, SolutionType, Source } from '../types';

export const demoProblems: Problem[] = [
  {
    id: '9001',
    title: 'Local-first incident knowledge base for small engineering teams',
    description: 'Teams lose debugging history across Slack threads, tickets, and postmortems. Build a searchable incident memory that links symptoms, fixes, owners, and follow-up tasks.',
    humanExplanation: 'A practical backend-heavy project with search, auth, structured notes, and workflow design. It shows you can build software teams would actually use.',
    techStack: ['FastAPI', 'PostgreSQL', 'React', 'Search'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '2-3 weeks',
    source: Source.GITHUB,
    sourceUrl: 'https://github.com/search?q=incident+knowledge+base&type=issues',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 38,
    collaboratorsCount: 4,
    createdAt: new Date().toISOString(),
    engineeringImpactScore: 86,
    technicalDepthScore: 0.84,
    industryImpactScore: 0.82,
    cognitiveComplexityScore: 0.76,
    signalQualityScore: 0.9,
    isNew: true,
  },
  {
    id: '9002',
    title: 'API latency regression monitor for FastAPI deployments',
    description: 'A lightweight observability dashboard that tracks endpoint latency, error rate, slow queries, and deploy-to-deploy regressions for small backend projects.',
    humanExplanation: 'This is a strong portfolio fit because it connects backend engineering, database design, metrics, and production awareness.',
    techStack: ['FastAPI', 'PostgreSQL', 'Recharts', 'Docker'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '1-2 weeks',
    source: Source.STACKOVERFLOW,
    sourceUrl: 'https://stackoverflow.com/questions/tagged/fastapi',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 27,
    collaboratorsCount: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    engineeringImpactScore: 78,
    technicalDepthScore: 0.72,
    industryImpactScore: 0.74,
    cognitiveComplexityScore: 0.66,
    signalQualityScore: 0.8,
  },
  {
    id: '9003',
    title: 'Resume-aware project recommender for junior developers',
    description: 'Given a resume and target role, recommend project ideas that fill skill gaps and produce measurable portfolio bullets.',
    humanExplanation: 'A focused AI-assisted full-stack project that can demonstrate parsing, ranking, UX, and practical career value.',
    techStack: ['React', 'Python', 'Embeddings', 'PostgreSQL'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '2 weeks',
    source: Source.HACKERNEWS,
    sourceUrl: 'https://news.ycombinator.com/',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 44,
    collaboratorsCount: 5,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    engineeringImpactScore: 81,
    technicalDepthScore: 0.7,
    industryImpactScore: 0.88,
    cognitiveComplexityScore: 0.69,
    signalQualityScore: 0.86,
  },
  {
    id: '9004',
    title: 'Offline-first field service checklist app',
    description: 'Technicians need structured checklists that work without network access, then sync cleanly with conflict resolution when back online.',
    humanExplanation: 'This has real system-design depth: offline storage, sync, conflict handling, audit trails, and role-based access.',
    techStack: ['IndexedDB', 'FastAPI', 'PostgreSQL', 'Sync'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '3 weeks',
    source: Source.REDDIT,
    sourceUrl: 'https://www.reddit.com/r/softwarearchitecture/',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 19,
    collaboratorsCount: 2,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    engineeringImpactScore: 74,
    technicalDepthScore: 0.81,
    industryImpactScore: 0.7,
    cognitiveComplexityScore: 0.79,
    signalQualityScore: 0.68,
  },
  {
    id: '9005',
    title: 'Developer onboarding map from repository history',
    description: 'New contributors struggle to understand where business logic lives. Analyze repos and generate a guided map of modules, owners, hotspots, and first issues.',
    humanExplanation: 'A strong GitHub/API/search project that shows practical developer-tool thinking.',
    techStack: ['GitHub API', 'Python', 'Graph', 'React'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '2-4 weeks',
    source: Source.GITHUB,
    sourceUrl: 'https://github.com/search?q=onboarding&type=issues',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 31,
    collaboratorsCount: 4,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    engineeringImpactScore: 83,
    technicalDepthScore: 0.85,
    industryImpactScore: 0.77,
    cognitiveComplexityScore: 0.82,
    signalQualityScore: 0.79,
  },
  {
    id: '9006',
    title: 'Secure API key rotation dashboard for small SaaS teams',
    description: 'Small teams often rotate secrets manually. Build a dashboard that tracks owners, expiry windows, audit events, and rotation playbooks.',
    humanExplanation: 'This fits backend/security positioning well: auth, audit logs, PostgreSQL schemas, and operational UX.',
    techStack: ['FastAPI', 'JWT', 'PostgreSQL', 'Security'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '1-2 weeks',
    source: Source.STACKOVERFLOW,
    sourceUrl: 'https://stackoverflow.com/questions/tagged/security',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 22,
    collaboratorsCount: 2,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    engineeringImpactScore: 76,
    technicalDepthScore: 0.73,
    industryImpactScore: 0.8,
    cognitiveComplexityScore: 0.62,
    signalQualityScore: 0.74,
  },
];

export const demoSquads = [
  {
    id: 9101,
    name: 'Latency Watch',
    description: 'Building a clean MVP for API regression monitoring with FastAPI middleware and dashboard charts.',
    problem_id: 9002,
    problem_title: 'API latency regression monitor for FastAPI deployments',
    leader_id: 1,
    leader_username: 'demo_lead',
    member_count: 3,
    pending_requests: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 9102,
    name: 'Incident Memory',
    description: 'Designing the schema, search flow, and incident timeline UX for engineering teams.',
    problem_id: 9001,
    problem_title: 'Local-first incident knowledge base for small engineering teams',
    leader_id: 2,
    leader_username: 'backend_varsha',
    member_count: 4,
    pending_requests: 0,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];
