import { Difficulty, Problem, SolutionType, Source } from '../types';

const baseDemoProblems: Problem[] = [
  {
    id: '9001',
    title: 'Local-first incident knowledge base for small engineering teams',
    description: 'Teams lose debugging history across Slack threads, tickets, and postmortems. Build a searchable incident memory that links symptoms, fixes, owners, and follow-up tasks.',
    humanExplanation: 'A practical backend-heavy project with search, auth, structured notes, and workflow design. It shows you can build software teams would actually use.',
    techStack: ['FastAPI', 'PostgreSQL', 'React', 'Search'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '2-3 weeks',
    source: Source.GITHUB,
    sourceUrl: 'https://github.com/search?q=incident+knowledge+base&type=issues',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 38,
    collaboratorsCount: 4,
    createdAt: new Date().toISOString(),
    engineeringImpactScore: 86,
    technicalDepthScore: 0.84,
    industryImpactScore: 0.82,
    cognitiveComplexityScore: 0.76,
    signalQualityScore: 0.9,
    isNew: true,
  },
  {
    id: '9002',
    title: 'API latency regression monitor for FastAPI deployments',
    description: 'A lightweight observability dashboard that tracks endpoint latency, error rate, slow queries, and deploy-to-deploy regressions for small backend projects.',
    humanExplanation: 'This is a strong portfolio fit because it connects backend engineering, database design, metrics, and production awareness.',
    techStack: ['FastAPI', 'PostgreSQL', 'Recharts', 'Docker'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '1-2 weeks',
    source: Source.STACKOVERFLOW,
    sourceUrl: 'https://stackoverflow.com/questions/tagged/fastapi',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 27,
    collaboratorsCount: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    engineeringImpactScore: 78,
    technicalDepthScore: 0.72,
    industryImpactScore: 0.74,
    cognitiveComplexityScore: 0.66,
    signalQualityScore: 0.8,
  },
  {
    id: '9003',
    title: 'Resume-aware project recommender for junior developers',
    description: 'Given a resume and target role, recommend project ideas that fill skill gaps and produce measurable portfolio bullets.',
    humanExplanation: 'A focused AI-assisted full-stack project that can demonstrate parsing, ranking, UX, and practical career value.',
    techStack: ['React', 'Python', 'Embeddings', 'PostgreSQL'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '2 weeks',
    source: Source.HACKERNEWS,
    sourceUrl: 'https://news.ycombinator.com/',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 44,
    collaboratorsCount: 5,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    engineeringImpactScore: 81,
    technicalDepthScore: 0.7,
    industryImpactScore: 0.88,
    cognitiveComplexityScore: 0.69,
    signalQualityScore: 0.86,
  },
  {
    id: '9004',
    title: 'Offline-first field service checklist app',
    description: 'Technicians need structured checklists that work without network access, then sync cleanly with conflict resolution when back online.',
    humanExplanation: 'This has real system-design depth: offline storage, sync, conflict handling, audit trails, and role-based access.',
    techStack: ['IndexedDB', 'FastAPI', 'PostgreSQL', 'Sync'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '3 weeks',
    source: Source.REDDIT,
    sourceUrl: 'https://www.reddit.com/r/softwarearchitecture/',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 19,
    collaboratorsCount: 2,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    engineeringImpactScore: 74,
    technicalDepthScore: 0.81,
    industryImpactScore: 0.7,
    cognitiveComplexityScore: 0.79,
    signalQualityScore: 0.68,
  },
  {
    id: '9005',
    title: 'Developer onboarding map from repository history',
    description: 'New contributors struggle to understand where business logic lives. Analyze repos and generate a guided map of modules, owners, hotspots, and first issues.',
    humanExplanation: 'A strong GitHub/API/search project that shows practical developer-tool thinking.',
    techStack: ['GitHub API', 'Python', 'Graph', 'React'],
    difficulty: Difficulty.ADVANCED,
    estimatedEffort: '2-4 weeks',
    source: Source.GITHUB,
    sourceUrl: 'https://github.com/search?q=onboarding&type=issues',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 31,
    collaboratorsCount: 4,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    engineeringImpactScore: 83,
    technicalDepthScore: 0.85,
    industryImpactScore: 0.77,
    cognitiveComplexityScore: 0.82,
    signalQualityScore: 0.79,
  },
  {
    id: '9006',
    title: 'Secure API key rotation dashboard for small SaaS teams',
    description: 'Small teams often rotate secrets manually. Build a dashboard that tracks owners, expiry windows, audit events, and rotation playbooks.',
    humanExplanation: 'This fits backend/security positioning well: auth, audit logs, PostgreSQL schemas, and operational UX.',
    techStack: ['FastAPI', 'JWT', 'PostgreSQL', 'Security'],
    difficulty: Difficulty.INTERMEDIATE,
    estimatedEffort: '1-2 weeks',
    source: Source.STACKOVERFLOW,
    sourceUrl: 'https://stackoverflow.com/questions/tagged/security',
    solutionType: SolutionType.SOFTWARE,
    interestedCount: 22,
    collaboratorsCount: 2,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    engineeringImpactScore: 76,
    technicalDepthScore: 0.73,
    industryImpactScore: 0.8,
    cognitiveComplexityScore: 0.62,
    signalQualityScore: 0.74,
  },
];

const sourceUrls: Record<Source, string> = {
  [Source.GITHUB]: 'https://github.com/search?q=portfolio+project+ideas&type=issues',
  [Source.STACKOVERFLOW]: 'https://stackoverflow.com/questions/tagged/software-design',
  [Source.HACKERNEWS]: 'https://news.ycombinator.com/',
  [Source.REDDIT]: 'https://www.reddit.com/r/softwarearchitecture/',
};

const additionalDemoProblems = [
  {
    title: 'Multi-tenant feature flag audit trail for B2B SaaS',
    description: 'Product teams need to know who changed a rollout, which customers were affected, and how to roll back safely when a flag causes a production issue.',
    humanExplanation: 'This turns a simple toggle system into a production-grade audit, permissions, and rollback workflow.',
    techStack: ['FastAPI', 'PostgreSQL', 'React', 'Audit Logs'],
    source: Source.GITHUB,
  },
  {
    title: 'Clinic no-show prediction and waitlist optimizer',
    description: 'Small clinics lose capacity when patients miss appointments. Build a dashboard that predicts risky slots, suggests reminders, and fills openings from a waitlist.',
    humanExplanation: 'A credible healthcare operations project with prediction, scheduling, and measurable business impact.',
    techStack: ['Python', 'FastAPI', 'PostgreSQL', 'React'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Personal finance anomaly detector for subscription creep',
    description: 'Users often miss duplicate charges, silent subscription increases, and unusual merchant patterns. Detect anomalies and explain them in plain language.',
    humanExplanation: 'This shows data modeling, alerts, explainability, and consumer-grade UX in one tight product.',
    techStack: ['Plaid API', 'Python', 'PostgreSQL', 'React'],
    source: Source.REDDIT,
  },
  {
    title: 'Teacher workload planner with rubric-aware grading queues',
    description: 'Teachers need to balance grading, feedback quality, and deadline pressure. Prioritize submissions by risk, rubric complexity, and student support needs.',
    humanExplanation: 'A practical edtech workflow that needs more than CRUD: prioritization logic and thoughtful UX matter.',
    techStack: ['React', 'FastAPI', 'PostgreSQL', 'Queueing'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'Pull request risk scorer for small engineering teams',
    description: 'Reviewers need a fast way to spot risky PRs. Score changes using touched modules, churn, tests, ownership, and historical incident links.',
    humanExplanation: 'A serious developer-tool idea combining GitHub APIs, analytics, ranking, and review workflow design.',
    techStack: ['GitHub API', 'Python', 'GraphQL', 'React'],
    source: Source.GITHUB,
  },
  {
    title: 'Customer support duplicate ticket clusterer',
    description: 'Support teams waste time triaging repeated reports of the same bug. Cluster incoming tickets, surface likely root causes, and link related incidents.',
    humanExplanation: 'This feels product-ready because it connects AI search with a real team workflow and cost savings.',
    techStack: ['Embeddings', 'FastAPI', 'PostgreSQL', 'React'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Warehouse cold-chain breach monitor',
    description: 'Food and pharma teams need to track temperature excursions, affected batches, compliance notes, and escalation timelines from sensor feeds.',
    humanExplanation: 'A high-impact operations app with monitoring, compliance, timeline UX, and audit trails.',
    techStack: ['IoT', 'FastAPI', 'Timeseries', 'React'],
    source: Source.REDDIT,
  },
  {
    title: 'Open-source maintainer burnout signal dashboard',
    description: 'Popular repositories accumulate issues faster than maintainers can respond. Detect burnout signals from response times, stale labels, and contributor load.',
    humanExplanation: 'A thoughtful GitHub analytics project with a human angle and strong visualization potential.',
    techStack: ['GitHub API', 'PostgreSQL', 'React', 'Analytics'],
    source: Source.GITHUB,
  },
  {
    title: 'Secure document expiry tracker for HR teams',
    description: 'HR teams need reminders for contracts, visas, certifications, and policy acknowledgements with role-based access and audit history.',
    humanExplanation: 'This demonstrates auth, RBAC, scheduled jobs, and polished operational workflow design.',
    techStack: ['FastAPI', 'PostgreSQL', 'RBAC', 'React'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'AI prompt regression test suite for product teams',
    description: 'Teams changing prompts need to know whether outputs got worse. Store test cases, compare model responses, and flag quality regressions before release.',
    humanExplanation: 'Very current and impressive: it frames AI as software quality engineering, not just a chat wrapper.',
    techStack: ['Python', 'FastAPI', 'LLM Eval', 'React'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Municipal issue routing system for citizen reports',
    description: 'City staff receive duplicate pothole, lighting, and sanitation reports. Route issues by location, category, urgency, and department capacity.',
    humanExplanation: 'A civic-tech project with maps, deduplication, routing, and admin workflows recruiters can understand quickly.',
    techStack: ['GIS', 'FastAPI', 'PostgreSQL', 'React'],
    source: Source.REDDIT,
  },
  {
    title: 'Release notes generator from commits and tickets',
    description: 'Teams struggle to turn commits and Jira tickets into useful customer-facing release notes. Generate grouped, editable notes with risk labels.',
    humanExplanation: 'A strong product-engineering demo because it turns messy engineering metadata into customer value.',
    techStack: ['GitHub API', 'NLP', 'FastAPI', 'React'],
    source: Source.GITHUB,
  },
  {
    title: 'Restaurant prep demand forecaster',
    description: 'Small restaurants need to estimate prep quantities from reservations, weather, events, and historical sales to reduce waste and stockouts.',
    humanExplanation: 'A grounded forecasting app where impact is easy to see: less waste, fewer stockouts, better planning.',
    techStack: ['Python', 'Forecasting', 'PostgreSQL', 'Dashboard'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Security checklist evidence collector for startups',
    description: 'Startups preparing for vendor reviews need to gather policies, screenshots, access reviews, and evidence into a repeatable security packet.',
    humanExplanation: 'This feels professional because it models real compliance work and evidence lifecycle management.',
    techStack: ['FastAPI', 'S3', 'PostgreSQL', 'React'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'Student project scope validator',
    description: 'Students often choose projects that are too broad or too shallow. Score scope, suggest MVP boundaries, and produce milestone plans.',
    humanExplanation: 'A meta-project that directly supports portfolio building and shows product empathy for junior developers.',
    techStack: ['React', 'FastAPI', 'Rules Engine', 'PostgreSQL'],
    source: Source.REDDIT,
  },
  {
    title: 'Cloud cost spike explainer for side projects',
    description: 'Developers get surprised by cloud bills. Ingest usage exports, detect spikes, map them to deploys, and explain the likely cause.',
    humanExplanation: 'This adds production credibility: cost awareness, deploy correlation, and actionable incident-style explanations.',
    techStack: ['AWS Cost Explorer', 'Python', 'React', 'PostgreSQL'],
    source: Source.GITHUB,
  },
  {
    title: 'Internal tool access review assistant',
    description: 'Managers need quarterly access reviews that are not spreadsheet chaos. Show who has access, why, last activity, and suggested removals.',
    humanExplanation: 'A clean security workflow with RBAC, audit logs, recommendations, and manager-friendly UX.',
    techStack: ['FastAPI', 'PostgreSQL', 'RBAC', 'React'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Remote team decision log with context recovery',
    description: 'Remote teams forget why decisions were made. Capture decisions, alternatives, owners, source links, and revisit dates in a searchable timeline.',
    humanExplanation: 'A knowledge-management app that rewards careful information architecture and search design.',
    techStack: ['PostgreSQL', 'Search', 'React', 'FastAPI'],
    source: Source.REDDIT,
  },
  {
    title: 'API contract drift detector for microservices',
    description: 'Frontend and backend teams break each other when APIs drift. Compare OpenAPI snapshots, identify breaking changes, and notify owners.',
    humanExplanation: 'This is a very engineering-heavy project with CI integration and clear production value.',
    techStack: ['OpenAPI', 'FastAPI', 'PostgreSQL', 'CI'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'Community moderation queue prioritizer',
    description: 'Moderators need to triage reports by harm, repeat offenders, confidence, and freshness while keeping an audit trail of actions.',
    humanExplanation: 'A nuanced trust-and-safety workflow with prioritization, auditability, and sensitive product decisions.',
    techStack: ['React', 'FastAPI', 'PostgreSQL', 'Moderation'],
    source: Source.REDDIT,
  },
  {
    title: 'Medication refill coordination tracker',
    description: 'Patients, pharmacies, and clinics lose time coordinating refills. Track refill status, blockers, messages, and escalation deadlines.',
    humanExplanation: 'A healthcare workflow app with roles, state machines, notifications, and real-world operational pressure.',
    techStack: ['FastAPI', 'PostgreSQL', 'React', 'Notifications'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Test flakiness investigator for CI pipelines',
    description: 'Teams ignore flaky tests until confidence collapses. Track flaky runs, environment patterns, recent code owners, and quarantine decisions.',
    humanExplanation: 'A recruiter-friendly developer productivity project with analytics and immediate engineering relevance.',
    techStack: ['CI API', 'Python', 'PostgreSQL', 'React'],
    source: Source.GITHUB,
  },
  {
    title: 'Vendor risk questionnaire auto-fill workspace',
    description: 'Security and sales teams repeatedly answer similar questionnaires. Reuse approved answers, flag stale evidence, and track review status.',
    humanExplanation: 'This blends search, permissions, approval workflow, and business-facing product polish.',
    techStack: ['FastAPI', 'PostgreSQL', 'Search', 'React'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'Local service outage map for small ISPs',
    description: 'Small ISPs need to combine customer reports, router telemetry, and field technician updates into a real-time outage map.',
    humanExplanation: 'A visually impressive real-time project with maps, WebSockets, and operational state tracking.',
    techStack: ['Maps', 'WebSockets', 'FastAPI', 'PostgreSQL'],
    source: Source.REDDIT,
  },
  {
    title: 'Knowledge base freshness monitor',
    description: 'Support docs silently rot as products change. Detect stale articles from ticket deflections, product changes, and unanswered searches.',
    humanExplanation: 'A smart support analytics project that shows you can connect user behavior to content quality.',
    techStack: ['Search Analytics', 'FastAPI', 'PostgreSQL', 'React'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Interview prep tracker tied to target job descriptions',
    description: 'Candidates need to map practice sessions to actual role requirements. Track gaps, spaced repetition, and evidence-ready project stories.',
    humanExplanation: 'This fits the portfolio theme while showing NLP, planning, and a polished personal-growth workflow.',
    techStack: ['React', 'FastAPI', 'PostgreSQL', 'NLP'],
    source: Source.REDDIT,
  },
  {
    title: 'Privacy request workflow for small apps',
    description: 'Small teams need a GDPR-style workflow for export/delete requests, identity checks, deadlines, and audit logs without buying enterprise tools.',
    humanExplanation: 'This is production-minded: privacy, state transitions, deadlines, background jobs, and auditability.',
    techStack: ['FastAPI', 'PostgreSQL', 'Background Jobs', 'React'],
    source: Source.STACKOVERFLOW,
  },
  {
    title: 'Fleet maintenance early warning board',
    description: 'Operations teams need to predict vehicle issues using service history, driver reports, mileage, and parts availability.',
    humanExplanation: 'A strong operations analytics concept with forecasting, inventory awareness, and maintenance workflows.',
    techStack: ['Python', 'PostgreSQL', 'React', 'Forecasting'],
    source: Source.HACKERNEWS,
  },
  {
    title: 'Meeting action item accountability tracker',
    description: 'Action items disappear after meetings. Extract tasks, assign owners, track blockers, and link outcomes back to decisions.',
    humanExplanation: 'A familiar productivity pain point with deeper workflow value than a basic notes app.',
    techStack: ['NLP', 'FastAPI', 'PostgreSQL', 'React'],
    source: Source.REDDIT,
  },
  {
    title: 'Dependency upgrade blast-radius planner',
    description: 'Teams delay dependency upgrades because impact is unclear. Map packages to services, tests, owners, vulnerabilities, and rollout steps.',
    humanExplanation: 'A mature developer tooling project with security, graph thinking, and release planning depth.',
    techStack: ['Dependency Graph', 'Python', 'PostgreSQL', 'React'],
    source: Source.GITHUB,
  },
];

export const demoProblems: Problem[] = [
  ...baseDemoProblems,
  ...additionalDemoProblems.map((problem, index): Problem => {
    const score = 72 + ((index * 7) % 22);
    return {
      id: String(9010 + index),
      title: problem.title,
      description: problem.description,
      humanExplanation: problem.humanExplanation,
      techStack: problem.techStack,
      difficulty: score >= 84 ? Difficulty.ADVANCED : Difficulty.INTERMEDIATE,
      estimatedEffort: index % 3 === 0 ? '2-3 weeks' : index % 3 === 1 ? '1-2 weeks' : '3-4 weeks',
      source: problem.source,
      sourceUrl: sourceUrls[problem.source],
      solutionType: SolutionType.SOFTWARE,
      interestedCount: 18 + ((index * 9) % 55),
      collaboratorsCount: 1 + ((index * 3) % 6),
      createdAt: new Date(Date.now() - (index + 6) * 86400000).toISOString(),
      engineeringImpactScore: score,
      technicalDepthScore: Number((0.58 + ((index * 5) % 33) / 100).toFixed(2)),
      industryImpactScore: Number((0.6 + ((index * 7) % 31) / 100).toFixed(2)),
      cognitiveComplexityScore: Number((0.55 + ((index * 11) % 35) / 100).toFixed(2)),
      signalQualityScore: Number((0.62 + ((index * 13) % 29) / 100).toFixed(2)),
      isNew: index < 4,
    };
  }),
];

export const demoSquads = [
  {
    id: 9101,
    name: 'Latency Watch',
    description: 'Building a clean MVP for API regression monitoring with FastAPI middleware and dashboard charts.',
    problem_id: 9002,
    problem_title: 'API latency regression monitor for FastAPI deployments',
    leader_id: 1,
    leader_username: 'demo_lead',
    member_count: 3,
    pending_requests: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 9102,
    name: 'Incident Memory',
    description: 'Designing the schema, search flow, and incident timeline UX for engineering teams.',
    problem_id: 9001,
    problem_title: 'Local-first incident knowledge base for small engineering teams',
    leader_id: 2,
    leader_username: 'backend_varsha',
    member_count: 4,
    pending_requests: 0,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 9103,
    name: 'PR Risk Lab',
    description: 'Exploring GitHub signals, ownership metadata, and test coverage to flag risky pull requests.',
    problem_id: 9014,
    problem_title: 'Pull request risk scorer for small engineering teams',
    leader_id: 3,
    leader_username: 'demo_builder',
    member_count: 5,
    pending_requests: 2,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 9104,
    name: 'Prompt QA Bench',
    description: 'Creating repeatable prompt regression tests for product teams shipping AI features.',
    problem_id: 9019,
    problem_title: 'AI prompt regression test suite for product teams',
    leader_id: 4,
    leader_username: 'qa_mira',
    member_count: 4,
    pending_requests: 1,
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 9105,
    name: 'Cold Chain Ops',
    description: 'Mapping sensor alerts, affected batches, and compliance evidence for warehouse teams.',
    problem_id: 9016,
    problem_title: 'Warehouse cold-chain breach monitor',
    leader_id: 5,
    leader_username: 'ops_arya',
    member_count: 3,
    pending_requests: 0,
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
];
